name: Determine Secrets
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  getSecrets:
    description: Comma-separated list of Secrets to get. Secrets preceded by an asterisk are returned encrypted
    required: true
  useGhTokenWorkflowForPush:
    description: Determines whether you want to use the GhTokenWorkflow secret for TokenForPush
    required: false
    default: 'false'
outputs:
  FORMATSTR:
    description: A format string to be used when transferring the secrets to ReadSecrets
    value: ${{ steps.DetermineSecrets.outputs.FORMATSTR }}
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      id: DetermineSecrets
      env:
        _getSecrets: ${{ inputs.getSecrets }}
        _useGhTokenWorkflowForPush: ${{ inputs.useGhTokenWorkflowForPush }}
      run: |
        ${{ github.action_path }}/../Invoke-AlGoAction.ps1 -ActionName "DetermineSecrets" -Action {
          ${{ github.action_path }}/DetermineSecrets.ps1 -getSecrets $ENV:_getSecrets -useGhTokenWorkflowForPush $ENV:_useGhTokenWorkflowForPush
        }
branding:
  icon: terminal
  color: blue
