name: Feature request
description: Suggest a feature you would like to see in AL-Go for GitHub
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: Please describe the feature you would like to see in AL-Go for GitHub
      placeholder: I would like to see...
    validations:
      required: true
