name: Test Workflow Input
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  workflowName:
    description: Name of the workflow
    required: false
    default: ${{ github.workflow }}
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      env:
        _workflowName: ${{ inputs.workflowName }}
      run: |
        ${{ github.action_path }}/../Invoke-AlGoAction.ps1 -ActionName "TestWorkflowInput" -Action {
          ${{ github.action_path }}/TestWorkflowInput.ps1 -workflowName $env:_workflowName
        }
branding:
  icon: terminal
  color: blue
