name: 2.0.$(Year:yy)$(DayOfYear).$(Rev:r)
trigger:
  branches:
    include:
      - main

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/heads/main

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: d365bc-agentpool-nonprod-1ESPT
    stages:
    - stage: ComponentGovernanceStage
      jobs:
      - job: ComponentGovernanceJob
        displayName: 'Component Governance'
        steps:      
        - powershell: |
            $req = Import-PowerShellDataFile -Path 'Actions/requirements.psd1'
            foreach ($mod in $req.RequiredModules) {
                Write-host "Installing $($mod.ModuleName) with version $($mod.ModuleVersion)"
                try {
                    Install-Module -Name $mod.ModuleName -RequiredVersion $mod.ModuleVersion -Scope CurrentUser -Force
                } catch {
                    Write-Host "Failed with error: $_"
                }
            }
        - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
          displayName: 'Component Detection'
          inputs:
            sourceScanPath: $(Agent.BuildDirectory)/s/Actions
            verbosity: 'Verbose'
