name: 'Troubleshooting'

on:
  workflow_dispatch:
    inputs:
      displayNameOfSecrets:
        description: Display the name (not the value) of secrets available to the repository
        type: boolean
        default: false

permissions:
  actions: read
  contents: read

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Troubleshooting:
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: true

      - name: Troubleshooting
        uses: microsoft/AL-Go-Actions/Troubleshooting@main
        with:
          shell: powershell
          gitHubSecrets: ${{ format(steps.DetermineSecrets.outputs.formatStr,toJSON(secrets[steps.DetermineSecrets.outputs.S0]),toJSON(secrets[steps.DetermineSecrets.outputs.S1]),toJSON(secrets[steps.DetermineSecrets.outputs.S2]),toJSON(secrets[steps.DetermineSecrets.outputs.S3]),toJSON(secrets[steps.DetermineSecrets.outputs.S4]),toJSON(secrets[steps.DetermineSecrets.outputs.S5]),toJSON(secrets[steps.DetermineSecrets.outputs.S6]),toJSON(secrets[steps.DetermineSecrets.outputs.S7]),toJSON(secrets[steps.DetermineSecrets.outputs.S8]),toJSON(secrets[steps.DetermineSecrets.outputs.S9]),toJSON(secrets[steps.DetermineSecrets.outputs.S10]),toJSON(secrets[steps.DetermineSecrets.outputs.S11]),toJSON(secrets[steps.DetermineSecrets.outputs.S12]),toJSON(secrets[steps.DetermineSecrets.outputs.S13]),toJSON(secrets[steps.DetermineSecrets.outputs.S14]),toJSON(secrets[steps.DetermineSecrets.outputs.S15]),toJSON(secrets[steps.DetermineSecrets.outputs.S16]),toJSON(secrets[steps.DetermineSecrets.outputs.S17]),toJSON(secrets[steps.DetermineSecrets.outputs.S18]),toJSON(secrets[steps.DetermineSecrets.outputs.S19]),toJSON(secrets[steps.DetermineSecrets.outputs.S20]),toJSON(secrets[steps.DetermineSecrets.outputs.S21]),toJSON(secrets[steps.DetermineSecrets.outputs.S22]),toJSON(secrets[steps.DetermineSecrets.outputs.S23]),toJSON(secrets[steps.DetermineSecrets.outputs.S24]),toJSON(secrets[steps.DetermineSecrets.outputs.S25]),toJSON(secrets[steps.DetermineSecrets.outputs.S26]),toJSON(secrets[steps.DetermineSecrets.outputs.S27]),toJSON(secrets[steps.DetermineSecrets.outputs.S28]),toJSON(secrets[steps.DetermineSecrets.outputs.S29]),toJSON(secrets[steps.DetermineSecrets.outputs.S30]),toJSON(secrets[steps.DetermineSecrets.outputs.S31])) }}
          displayNameOfSecrets: ${{ github.event.inputs.displayNameOfSecrets }}
