name: ' Update AL-Go System Files'

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: Template Repository URL (current is {TEMPLATEURL})
        required: false
        default: ''
      downloadLatest:
        description: Download latest from template repository
        type: boolean
        default: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false
      includeBranches:
        description: Specify a comma-separated list of branches to update. Wildcards are supported. The AL-Go settings will be read for every branch. Leave empty to update the current branch only.
        required: false
        default: ''

permissions:
  actions: read
  contents: read
  id-token: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Initialize:
    runs-on: windows-latest
    name: Initialize
    outputs:
      UpdateBranches: ${{ steps.GetBranches.outputs.Result }}
      TemplateUrl: ${{ steps.DetermineTemplateUrl.outputs.TemplateUrl }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Read settings
        id: ReadSettings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell
          get: templateUrl

      - name: Get Workflow Multi-Run Branches
        id: GetBranches
        uses: microsoft/AL-Go-Actions/GetWorkflowMultiRunBranches@main
        with:
          shell: powershell
          includeBranches: ${{ github.event.inputs.includeBranches }}

      - name: Determine Template URL
        id: DetermineTemplateUrl
        env:
          TemplateUrlAsInput: '${{ github.event.inputs.templateUrl }}'
        run: |
            $templateUrl = $env:templateUrl # Available from ReadSettings step
            if ($ENV:TemplateUrlAsInput) {
              # Use the input value if it is provided
              $templateUrl = $ENV:TemplateUrlAsInput
            }
            Write-Host "Using template URL: $templateUrl"
            Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "TemplateUrl=$templateUrl"

  UpdateALGoSystemFiles:
    name: "[${{ matrix.branch }}] Update AL-Go System Files"
    needs: [ Initialize ]
    runs-on: windows-latest
    strategy:
      matrix:
        branch: ${{ fromJson(needs.Initialize.outputs.UpdateBranches).branches }}
      fail-fast: false

    steps:
      - name: Dump Workflow Information
        uses: microsoft/AL-Go-Actions/DumpWorkflowInfo@main
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ matrix.branch }}

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@main
        with:
          shell: powershell

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell
          get: commitOptions

      - name: Determine secrets
        id: DetermineSecrets
        uses: microsoft/AL-Go-Actions/DetermineSecrets@main
        with:
          shell: powershell
          getSecrets: 'ghTokenWorkflow'

      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@main
        with:
          shell: powershell
          gitHubSecrets: ${{ format(steps.DetermineSecrets.outputs.formatStr,toJSON(secrets[env.S0]),toJSON(secrets[env.S1]),toJSON(secrets[env.S2]),toJSON(secrets[env.S3]),toJSON(secrets[env.S4]),toJSON(secrets[env.S5]),toJSON(secrets[env.S6]),toJSON(secrets[env.S7]),toJSON(secrets[env.S8]),toJSON(secrets[env.S9]),toJSON(secrets[env.S10]),toJSON(secrets[env.S11]),toJSON(secrets[env.S12]),toJSON(secrets[env.S13]),toJSON(secrets[env.S14]),toJSON(secrets[env.S15]),toJSON(secrets[env.S16]),toJSON(secrets[env.S17]),toJSON(secrets[env.S18]),toJSON(secrets[env.S19]),toJSON(secrets[env.S20]),toJSON(secrets[env.S21]),toJSON(secrets[env.S22]),toJSON(secrets[env.S23]),toJSON(secrets[env.S24]),toJSON(secrets[env.S25]),toJSON(secrets[env.S26]),toJSON(secrets[env.S27]),toJSON(secrets[env.S28]),toJSON(secrets[env.S29]),toJSON(secrets[env.S30]),toJSON(secrets[env.S31])) }}
          getSecrets: 'ghTokenWorkflow'

      - name: Calculate Commit Options
        env:
          directCommit: '${{ github.event.inputs.directCommit }}'
          downloadLatest: '${{ github.event.inputs.downloadLatest }}'
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          if('${{ github.event_name }}' -eq 'workflow_dispatch') {
            Write-Host "Using inputs from workflow_dispatch event"
            $directCommit = $env:directCommit
            $downloadLatest = $env:downloadLatest
          }
          else {
            Write-Host "Using inputs from commitOptions setting"
            $commitOptions = $env:commitOptions | ConvertFrom-Json # Available from ReadSettings step
            $directCommit=$(-not $commitOptions.createPullRequest)
            $downloadLatest=$true
          }
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "directCommit=$directCommit"
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "downloadLatest=$downloadLatest"

      - name: Update AL-Go system files
        uses: microsoft/AL-Go-Actions/CheckForUpdates@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          token: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }}
          downloadLatest: ${{ env.downloadLatest }}
          update: 'Y'
          templateUrl: ${{ needs.Initialize.outputs.TemplateUrl }}
          directCommit: ${{ env.directCommit }}
          updateBranch: ${{ matrix.branch }}

      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}
