name: Determine Artifacts Retention Days
author: Microsoft Corporation
description: Determines retention days for the artifacts produced by the workflow
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
outputs:
  ArtifactsRetentionDays:
    description: Artifacts retention days
    value: ${{ steps.determineArtifactsRetentionDays.outputs.ArtifactsRetentionDays }}
runs:
  using: composite
  steps:
    - name: Determine Projects to Build
      shell: ${{ inputs.shell }}
      id: determineArtifactsRetentionDays
      run: |
        ${{ github.action_path }}/../Invoke-AlGoAction.ps1 -ActionName "DetermineArtifactsRetentionDays" -Action {
          ${{ github.action_path }}/DetermineArtifactsRetentionDays.Action.ps1 -baseFolder ${{ github.workspace }} -token ${{ github.token }}
        }
branding:
  icon: terminal
  color: blue
