name: 'Add existing app or test app'

run-name: "Add existing app or test app in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      url:
        description: Direct Download Url of .app or .zip file
        required: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for PR/Commit?
        type: boolean
        default: false

permissions:
  actions: read
  contents: write
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  AddExistingAppOrTestApp:
    needs: [ ]
    runs-on: [ windows-latest ]
    steps:
      - name: Dump Workflow Information
        uses: microsoft/AL-Go-Actions/DumpWorkflowInfo@main
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@main
        with:
          shell: powershell

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell

      - name: Determine secrets
        id: DetermineSecrets
        uses: microsoft/AL-Go-Actions/DetermineSecrets@main
        with:
          shell: powershell
          getSecrets: 'TokenForPush'
          useGhTokenWorkflowForPush: '${{ github.event.inputs.useGhTokenWorkflow }}'

      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@main
        with:
          shell: powershell
          gitHubSecrets: ${{ format(steps.DetermineSecrets.outputs.formatStr,toJSON(secrets[steps.DetermineSecrets.outputs.S0]),toJSON(secrets[steps.DetermineSecrets.outputs.S1]),toJSON(secrets[steps.DetermineSecrets.outputs.S2]),toJSON(secrets[steps.DetermineSecrets.outputs.S3]),toJSON(secrets[steps.DetermineSecrets.outputs.S4]),toJSON(secrets[steps.DetermineSecrets.outputs.S5]),toJSON(secrets[steps.DetermineSecrets.outputs.S6]),toJSON(secrets[steps.DetermineSecrets.outputs.S7]),toJSON(secrets[steps.DetermineSecrets.outputs.S8]),toJSON(secrets[steps.DetermineSecrets.outputs.S9]),toJSON(secrets[steps.DetermineSecrets.outputs.S10]),toJSON(secrets[steps.DetermineSecrets.outputs.S11]),toJSON(secrets[steps.DetermineSecrets.outputs.S12]),toJSON(secrets[steps.DetermineSecrets.outputs.S13]),toJSON(secrets[steps.DetermineSecrets.outputs.S14]),toJSON(secrets[steps.DetermineSecrets.outputs.S15]),toJSON(secrets[steps.DetermineSecrets.outputs.S16]),toJSON(secrets[steps.DetermineSecrets.outputs.S17]),toJSON(secrets[steps.DetermineSecrets.outputs.S18]),toJSON(secrets[steps.DetermineSecrets.outputs.S19]),toJSON(secrets[steps.DetermineSecrets.outputs.S20]),toJSON(secrets[steps.DetermineSecrets.outputs.S21]),toJSON(secrets[steps.DetermineSecrets.outputs.S22]),toJSON(secrets[steps.DetermineSecrets.outputs.S23]),toJSON(secrets[steps.DetermineSecrets.outputs.S24]),toJSON(secrets[steps.DetermineSecrets.outputs.S25]),toJSON(secrets[steps.DetermineSecrets.outputs.S26]),toJSON(secrets[steps.DetermineSecrets.outputs.S27]),toJSON(secrets[steps.DetermineSecrets.outputs.S28]),toJSON(secrets[steps.DetermineSecrets.outputs.S29]),toJSON(secrets[steps.DetermineSecrets.outputs.S30]),toJSON(secrets[steps.DetermineSecrets.outputs.S31])) }}
          useGhTokenWorkflowForPush: '${{ github.event.inputs.useGhTokenWorkflow }}'

      - name: Add existing app
        uses: microsoft/AL-Go-Actions/AddExistingApp@main
        with:
          shell: powershell
          token: ${{ steps.ReadSecrets.outputs.TokenForPush }}
          project: ${{ github.event.inputs.project }}
          url: ${{ github.event.inputs.url }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}
