name: ' Update AL-Go System Files'

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: Template Repository URL (current is {TEMPLATEURL})
        required: false
        default: ''
      downloadLatest:
        description: Download latest from template repository
        type: boolean
        default: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false

permissions:
  actions: read
  contents: read
  id-token: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  GetBranches:
    runs-on: windows-latest
    name: Get Supported Branches
    outputs:
      SupportedBranches: ${{ steps.DetermineBranches.outputs.Result }}
    steps:
      - name: Checkout
        if: ${{ github.event_name == 'schedule' }}
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Read settings
        id: ReadSettings
        if: ${{ github.event_name == 'schedule' }}
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell
          get: scheduleSettings

      - name: Get Supported Branches
        if: ${{ github.event_name == 'schedule' }}
        id: GetSupportedBranches
        uses: microsoft/AL-Go-Actions/GetGitBranches@main
        with:
          shell: powershell
          includeBranches: ${{ join(fromJson(env.scheduleSettings).includeBranches, ',') }}

      - name: Determine branches to update
        id: DetermineBranches
        env:
          supportedBranchesJson: ${{ steps.GetSupportedBranches.outputs.Branches }}
        run: |
            $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0

            if ('${{ github.event_name }}' -eq 'schedule') {
              Write-Host "Running 'Update AL-Go System Files' on a schedule."

              $supportedBranches = ConvertFrom-Json $env:supportedBranchesJson
              Write-Host "Supported Branches: $($supportedBranches -join ', ')"
              Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "Result=$env:supportedBranchesJson"
            }
            else {
              Write-Host "Running Update AL-Go System Files on a manual trigger."
              Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "Result=['${{ github.ref_name }}']"
            }

  UpdateALGoSystemFiles:
    name: "[${{ matrix.branch }}] Update AL-Go System Files"
    needs: [ GetBranches ]
    runs-on: [ windows-latest ]
    strategy:
      matrix:
        branch: ${{ fromJson(needs.GetBranches.outputs.SupportedBranches) }}
      fail-fast: false

    steps:
      - name: Dump Workflow Information
        uses: microsoft/AL-Go-Actions/DumpWorkflowInfo@main
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ matrix.branch }}

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@main
        with:
          shell: powershell

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell
          get: templateUrl,commitOptions

      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@main
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'TokenForPush'
          useGhTokenWorkflowForPush: true

      - name: Override templateUrl
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          templateUrl: ${{ github.event.inputs.templateUrl }}
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $templateUrl = $ENV:templateUrl
          if ($templateUrl) {
            Write-Host "Using Template Url: $templateUrl"
            Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "templateUrl=$templateUrl"
          }

      - name: Calculate Input (manual trigger)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          directCommit: '${{ github.event.inputs.directCommit }}'
          downloadLatest: ${{ github.event.inputs.downloadLatest }}
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $directCommit = $ENV:directCommit
          $downloadLatest = $ENV:downloadLatest
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "directCommit=$directCommit"
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "downloadLatest=$downloadLatest"

      - name: Calculate Input (schedule trigger)
        if: ${{ github.event_name == 'schedule' }}
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0

          $commitOptions = $env:commitOptions | ConvertFrom-Json
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "directCommit=$(-not $commitOptions.createPullRequest)"
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "downloadLatest=$true"

      - name: Update AL-Go system files
        uses: microsoft/AL-Go-Actions/CheckForUpdates@main
        with:
          shell: powershell
          token: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).TokenForPush }}
          downloadLatest: ${{ env.downloadLatest }}
          update: 'Y'
          templateUrl: ${{ env.templateUrl }}
          directCommit: ${{ env.directCommit }}
          updateBranch: ${{ matrix.branch }}

      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}
