name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

permissions:
  contents: read

jobs:
  Test:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Harden Runner
        if: github.repository_owner == 'microsoft'
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run AL-Go Actions Tests
        run: |
          . (Join-Path "." "Tests/runtests.ps1") -Path "Tests"

      - name: Test AL-Go Workflows
        if: github.repository_owner == 'microsoft'
        run: |
          . (Join-Path "." "Tests/runtests.ps1") -Path "Tests/WorkflowSanitation"

      - name: Test aka.ms links in markdown files
        if: github.repository_owner == 'microsoft'
        run: |
          . (Join-Path "." "Tests/runtests.ps1") -Path "Tests/MarkdownLinks"
